<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SwiftList.PluginSdk</AssemblyName>
    <RootNamespace>SwiftList.PluginSdk</RootNamespace>
    <Version>1.5.3</Version>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

</Project>
